### ISSUE TITLE
Git laboratories

### ISSUE THREAD

**Issue by Mirciulica15** [Mirciulica15/DevOps-Tech-Summer-Practice-2024#15]
Introductory Killercoda Git laboratories [link](https://killercoda.com/pawelpiwosz/course/gitFundamentals)

**Comment by Mirciulica15** [comment]
# Place a ✅ in a comment below when you finish this task

**Comment by mariafelecann** [comment]
✅

**Comment by Flavu12** [comment]
✅

**Comment by Cosma-Dan-30126** [comment]
✅
